### ISSUE TITLE
Add Extended Abstract Template

### ISSUE THREAD

**Issue by Joao-M-Almeida** [themiguelamador/ThesisIST#6]
Faz sentido adicionar um template para o resumo alargado da Tese? Por exemplo [este](https://www.overleaf.com/latex/templates/extended-abstract-ist/sztsqmgmndsg) ?

**Comment by themiguelamador** [comment]
Tens este aqui, que foi o que usei: https://github.com/themiguelamador/LaTeXArticleTemplate1
Não tem sido muito mantido, mas segue a mesma linha deste.

**Comment by NBajanca** [comment]
Eu concordo com o @Joao-M-Almeida porque o resumo alargado é uma parte obrigatória da tese.

**Comment by themiguelamador** [comment]
Também concordo, daí remeter para o projecto onde tenho o artigo/resumo alargado, que podem usar, ainda que aqui o estilo varie consoante a área da tese, e não por regras definidas pelo IST.  https://github.com/themiguelamador/LaTeXArticleTemplate1 este segue a mesma lógica de pacotes e trabalho. Mas tem sido alvo de menos revisões do que o da tese.
